# 202302mduncan
Create a summary table from the taxa counts file. Include a sequencing effort metric.

Note: it would be good to check the counts of each sample from the taxa count spreadsheet against those reported after dada2 merging. Obviously some counts would be lost if they can't be assigned to taxa, but that might be an interesting observation.

## Create a table of raw species counts across samples

In [172]:
import pandas as pd

count_table = pd.read_table('../qiime2/12S/asvs/asv_count_tax.tsv')
count_table.head()

,Feature.ID,X01.BWL.D.MR8,X02.BWL.D.MR8,X03.BWL.U.MR7,X04.BWL.U.MR7,X05.BWL.1,X06.BWL.1,X07.BWL.1,X08.BWL.8,X09.BWL.8,...,X28.HW.3,X29.MIN.1,X30.MIN.1,X31.MIN.1,X32.MS.1,X33.MS.1,X34.MS.1,X35.MS.1,midori_Taxon,midori_Confidence
0,0141c63e4e0e71ab8407a5e1c4507334,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,0.999986
1,01dea82e257a4bff7ab243c1091841ec,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,0.999998
2,0208e84f3960c9d1cbfe1bdbbb9b8656,0,0,0,0,0,89,0,0,0,...,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,0.999789
3,023b29c8883be387e7f03d94f3a86d80,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,0.999614
4,028cd8e4c842caa082607fac05fc04e9,22,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,0.986142

In [173]:
#Drop the hash
count_table.drop('Feature.ID', inplace=True, axis=1)
count_table.head()

,X01.BWL.D.MR8,X02.BWL.D.MR8,X03.BWL.U.MR7,X04.BWL.U.MR7,X05.BWL.1,X06.BWL.1,X07.BWL.1,X08.BWL.8,X09.BWL.8,X10.BWL.8,...,X28.HW.3,X29.MIN.1,X30.MIN.1,X31.MIN.1,X32.MS.1,X33.MS.1,X34.MS.1,X35.MS.1,midori_Taxon,midori_Confidence
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,0.999986
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,0.999998
2,0,0,0,0,0,89,0,0,0,0,...,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,0.999789
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,0.999614
4,22,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,0.986142

In [174]:
count_table['midori_Confidence'].median()

0.9997424876202905

In [175]:
# drop confidence
count_table.drop('midori_Confidence', axis=1, inplace=True)
count_table.head()

,X01.BWL.D.MR8,X02.BWL.D.MR8,X03.BWL.U.MR7,X04.BWL.U.MR7,X05.BWL.1,X06.BWL.1,X07.BWL.1,X08.BWL.8,X09.BWL.8,X10.BWL.8,...,X27.HW.3,X28.HW.3,X29.MIN.1,X30.MIN.1,X31.MIN.1,X32.MS.1,X33.MS.1,X34.MS.1,X35.MS.1,midori_Taxon
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...
2,0,0,0,0,0,89,0,0,0,0,...,0,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...
4,22,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...

In [176]:
def fmt_taxonomy(taxonomy):
    tree = taxonomy.split(';')
    return tree[-1]

count_table['species'] = count_table['midori_Taxon'].apply(fmt_taxonomy)

In [177]:
count_table.drop('midori_Taxon', axis=1, inplace=True)
count_table.head()

,X01.BWL.D.MR8,X02.BWL.D.MR8,X03.BWL.U.MR7,X04.BWL.U.MR7,X05.BWL.1,X06.BWL.1,X07.BWL.1,X08.BWL.8,X09.BWL.8,X10.BWL.8,...,X27.HW.3,X28.HW.3,X29.MIN.1,X30.MIN.1,X31.MIN.1,X32.MS.1,X33.MS.1,X34.MS.1,X35.MS.1,species
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,s__Macquaria ambigua_135764
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,s__Macquaria ambigua_135764
2,0,0,0,0,0,89,0,0,0,0,...,0,0,0,0,0,0,0,0,0,s__Macquaria ambigua_135764
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,s__Macquaria ambigua_135764
4,22,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,s__Gadopsis bispinosus_135754

In [178]:
by_species = count_table.groupby('species').sum()
by_species.loc['sum'] = by_species.sum(axis=0)
by_species.to_csv('../results/raw_species_counts.csv')
by_species.tail()

,X01.BWL.D.MR8,X02.BWL.D.MR8,X03.BWL.U.MR7,X04.BWL.U.MR7,X05.BWL.1,X06.BWL.1,X07.BWL.1,X08.BWL.8,X09.BWL.8,X10.BWL.8,...,X26.HW.3,X27.HW.3,X28.HW.3,X29.MIN.1,X30.MIN.1,X31.MIN.1,X32.MS.1,X33.MS.1,X34.MS.1,X35.MS.1
species,,,,,,,,,,,,,,,,,,,,,
s__Macquaria australasica_135765,39,42,82,146,136,68,134,37,50,16,...,99,103,50,25,53,0,192,0,16,173
s__Nematalosa erebi_316163,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s__Retropinna semoni_182228,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,21,0,0,0,0,0
s__Tandanus tandanus_512777,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,9,0,0,9,0
sum,20287,27260,17115,39389,28866,27055,21864,16575,28775,17016,...,18106,22852,22423,23293,19249,5597,24131,18293,18160,22546

## Create a table of normalised species counts across samples
So I checked, and all OTUs could be assigned a taxa (at some level), so column sums actually repressent read count sums (ie there are no unallocated OUTs whose counts are dropped from the table). So all i have to do is divide each value by the column sum to give a relative abundance.

In [179]:
# drop the sum row as that will effect the column counts
by_species = by_species.iloc[:-1,:]
# divide by col sum
by_species_rel = by_species.div(by_species.sum(axis=0), axis=1)
by_species_rel.head()

,X01.BWL.D.MR8,X02.BWL.D.MR8,X03.BWL.U.MR7,X04.BWL.U.MR7,X05.BWL.1,X06.BWL.1,X07.BWL.1,X08.BWL.8,X09.BWL.8,X10.BWL.8,...,X26.HW.3,X27.HW.3,X28.HW.3,X29.MIN.1,X30.MIN.1,X31.MIN.1,X32.MS.1,X33.MS.1,X34.MS.1,X35.MS.1
species,,,,,,,,,,,,,,,,,,,,,
c__Actinopteri_186623,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.000987,0.0,0.0,0.0,0.000991,0.0
f__Hominidae_9604,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0
f__Percichthyidae_8162,0.000000,0.0,0.0,0.0,0.0,0.0,0.002012,0.000000,0.001703,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0
g__Carassius_7956,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.001872,0.0
g__Homo_9605,0.002908,0.0,0.0,0.0,0.0,0.0,0.000000,0.003137,0.000000,0.0,...,0.005247,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0

In [180]:
by_species_rel.loc['sum'] = by_species_rel.sum(axis=0)
by_species_rel
by_species_rel.to_csv('../results/relative_species_counts.csv')